[package]
name = "transform"
version = "0.1.0"
edition = "2021"
description = "RITE transformer trait"
readme = "README.md"
repository = "https://github.com/CIAO-systems/rite"
license = "Apache-2.0"

[dependencies]
model = { git = "https://github.com/CIAO-systems/rite-lib-model.git" }
